name: sherpa

channels:
  - conda-forge
  - astropy

dependencies:
  - bison
  - python=3.10
  - numpy
  - pandoc
  - matplotlib
  - astropy
  - pip
  - graphviz
  - sphinx<8.0
  - pip:
    - ipykernel
    - nbsphinx
    - sphinx-astropy
    - sphinx_rtd_theme>=3.0.0
    - bokeh
